import { PrismaClient } from "@prisma/client";
const db = new PrismaClient();

const categories = [
  "Electronics",
  "Fashion",
  "Home & Garden",
  "Books & Magazines",
  "Health & Beauty",
  "Toys & Hobbies",
  "Sports & Outdoors",
  "Automotive",
  "Baby Products",
  "Grocery & Gourmet Food",
  "Pet Supplies",
  "Computers & Accessories",
  "Jewelry",
  "Office Supplies",
  "Footwear",
  "Mobile Phones & Accessories",
  "Music, Movies, & Games",
  "Art & Craft Supplies",
  "Travel Accessories",
  "Handbags & Wallets",
  "Furniture",
  "Kitchen & Dining",
  "Bedding & Bath",
  "Tools & Home Improvement",
  "Camera & Photo",
  "Video Games",
  "Watches",
  "Outdoor Living",
  "Apparel",
  "Fitness Equipment",
  "Personal Care Appliances",
  "Gift Cards",
  "Antiques & Collectibles",
  "Musical Instruments",
  "Industrial & Scientific",
  "Printers & Ink",
  "Software",
  "Party Supplies",
  "School Supplies",
  "Maternity",
  "Wedding Supplies",
  "Eyewear",
  "Skin Care",
  "Hair Care",
  "Perfumes & Fragrances",
  "Nutrition & Wellness",
  "Medical Supplies",
  "Safety & Security",
  "Aquarium & Pet Care",
  "Gardening Supplies",
  "Cycling & Biking",
  "Boating & Fishing",
  "Camping & Hiking",
  "Winter Sports",
  "Water Sports",
  "Team Sports",
  "Fitness & Yoga",
  "Racquet Sports",
  "Golf Equipment",
  "Running Gear",
  "Surfing & Diving",
  "Climbing Gear",
  "Hunting & Shooting",
  "Horse Riding",
  "Motorcycle Gear",
  "Automotive Parts",
  "Car Electronics",
  "Tires & Wheels",
  "Car Care",
  "RV Parts & Accessories",
  "Baby Clothing",
  "Baby Gear",
  "Nursery Furniture",
  "Baby Toys",
  "Feeding & Nursing",
  "Baby Safety",
  "Diapering",
  "Maternity Clothing",
  "Snacks & Beverages",
  "Pantry Staples",
  "Fresh Produce",
  "Meat & Seafood",
  "Dairy & Eggs",
  "Bakery",
  "Frozen Food",
  "Specialty Foods",
  "Wine, Beer & Spirits",
  "Food Delivery Services",
  "Bird Supplies",
  "Cat Supplies",
  "Dog Supplies",
  "Fish Supplies",
  "Reptile & Amphibian Supplies",
  "Small Animal Supplies",
  "Farm & Ranch Supplies",
  "Vitamins & Dietary Supplements",
  "Pharmacy",
  "Televisions & Accessories",
  "Laptops & Notebooks",
  "Desktop Computers",
]

const seedCategories = async () => {
  try {
    const categoryRecords = categories.map((category) => ({
      name: category
    }))
    const uniqueCategories = Array.from(new Set(categoryRecords));
    await db.category.createMany({
      data: uniqueCategories,
      skipDuplicates: true,
    });
    return "seeded the database with categories"
  } catch (error) {                            
    console.log(error);
  }
};

seedCategories()
                                   